### ISSUE TITLE
maven-processor-plugin language support

### ISSUE THREAD

**Issue by ffurkAn** [bsorrentino/maven-annotation-plugin#89] opened 2020-12-03 13:30 UTC
Hi,

I am using the plugin below:

```xml
<plugin>
  <groupId>org.bsc.maven</groupId>
  <artifactId>maven-processor-plugin</artifactId>
  <version>3.3.3</version>
  <executions>
    <execution>
      <goals>
        <goal>process</goal>
      </goals>
      <phase>generate-sources</phase>
      <configuration>
        <compilerArguments>-AaddGeneratedAnnotation=false</compilerArguments>
        <!-- suppress java.annotation -->
        <processors>
          <processor>org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor</processor>
        </processors>
      </configuration>
    </execution>
  </executions>
</plugin>
```

OS language is Turkish. So, i becomes İ. Because of that, It causes error. How can I add language=EN support so that I resolve the issue?

kind regards

**Comment by bsorrentino** [comment] 2020-12-04 13:44
hi @ffurkAn do you mean change **encoding* ?

**Comment by bsorrentino** [comment] 2020-12-22 12:19
I guess it is a duplicate of #90

**Closed by bsorrentino** 2020-12-22 12:19 UTC
Labels: duplicate, question
